server:
  port: 7072

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: root
      database: hrmuserdb
#  security:
#    name: hrm
#    password: 123
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411/
#    service:
#      name: auth-service
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: hrm
#    password: 123
jwt:
  secretkey: ${hrm-secretkey}
  audience: ${hrm-audience}
  issuer: ${hrm-issuer}

#rabbitmq:
#  exchange-auth: auth-exchange
#  registerkey: register-key
#  queueRegister: register-queue
#  registerMailKey: mail-key
#  registerMailQueue: mail-queue